// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuJlusKOueTVi9Jbkh9VucWAj7TeL1lA',
    appId: '1:302736887742:web:5743db114b76b7a19ab3ef',
    messagingSenderId: '302736887742',
    projectId: 'shyam-mynotes-project',
    authDomain: 'shyam-mynotes-project.firebaseapp.com',
    storageBucket: 'shyam-mynotes-project.appspot.com',
    measurementId: 'G-03JX2KDWW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjmdM7cj0prqnu5i72LlJR3Ai_fwlUaA',
    appId: '1:302736887742:android:be7b40188ba990b49ab3ef',
    messagingSenderId: '302736887742',
    projectId: 'shyam-mynotes-project',
    storageBucket: 'shyam-mynotes-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEnQt1oQ1u4ZLslW7dMpfqIaoO7HFmVw',
    appId: '1:302736887742:ios:dd0b8c1222aadf2e9ab3ef',
    messagingSenderId: '302736887742',
    projectId: 'shyam-mynotes-project',
    storageBucket: 'shyam-mynotes-project.appspot.com',
    iosClientId: '302736887742-ptjrj5mu113ismvn3uc7ckh9le604lli.apps.googleusercontent.com',
    iosBundleId: 'com.suyogupta.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqEnQt1oQ1u4ZLslW7dMpfqIaoO7HFmVw',
    appId: '1:302736887742:ios:dd0b8c1222aadf2e9ab3ef',
    messagingSenderId: '302736887742',
    projectId: 'shyam-mynotes-project',
    storageBucket: 'shyam-mynotes-project.appspot.com',
    iosClientId: '302736887742-ptjrj5mu113ismvn3uc7ckh9le604lli.apps.googleusercontent.com',
    iosBundleId: 'com.suyogupta.mynotes',
  );
}
